# Generated by Django 2.2 on 2019-04-23 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190415_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issuesreported',
            old_name='text',
            new_name='issue_text',
        ),
        migrations.AddField(
            model_name='users',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.IssuesReported'),
        ),
    ]
